unit Setup4D.Utility.Enum;

interface
Type
{$SCOPEDENUMS ON}
  TSetup4DUtilityEstadoAbreviado = (_AC, _AL, _AP, _AM, _BA, _CE, _DF, _ES,
    _GO, _MA, _MT, _MS, _MG, _PA, _PB, _PR, _PE, _PI, _RJ, _RN, _RS, _RO, _RR,
    _SC, _SP, _SE, _TO);

  TSetup4DUtilityEstado = (ACRE, ALAGOAS, AMAPA, AMAZONAS, BAHIA, CEARA,
    DISTRITO_FEDERAL, ESPIRITO_SANTO, GOIAS, MARANHAO, MATO_GROSSO,
    MATO_GROSSO_DO_SUL, MINAS_GERAIS, PARA, PARAIBA, PARANA, PERNAMBUCO,
    PIAUI, RIO_DE_JANEIRO, RIO_GRANDE_DO_NORTE, RIO_GRANDE_DO_SUL, RONDONIA,
    RORAIMA, SANTA_CATARINA, SAO_PAULO, SERGIPE, TOCANTINS);
{$SCOPEDENUMS OFF}
implementation

end.
